import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === 'MY_GEMINI_API_KEY') {
      return NextResponse.json(
        {
          error:
            'Gemini API key is not configured. Please set the GEMINI_API_KEY environment secret in the AI Studio panel to activate AI PDF features.',
        },
        { status: 503 }
      );
    }

    const body = await req.json();
    const { action, text, question, targetLanguage = 'English', history = [] } = body;

    if (!text || typeof text !== 'string') {
      return NextResponse.json(
        { error: 'Document text context is required.' },
        { status: 400 }
      );
    }

    // Chunk or limit text context to 30,000 characters to ensure safe limits
    const safeTextContext = text.slice(0, 30000);

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });

    let prompt = '';
    let systemInstruction =
      'You are ZoraPDF AI, an intelligent document analysis assistant. Always provide factual, structured answers based strictly on the provided document context. If an answer cannot be deduced from the document, clarify that clearly without hallucinating.';

    if (action === 'chat') {
      if (!question) {
        return NextResponse.json({ error: 'Question is required for chat.' }, { status: 400 });
      }
      prompt = `Here is the content of the PDF document:
--- DOCUMENT START ---
${safeTextContext}
--- DOCUMENT END ---

User Question: ${question}

Please answer the user question accurately using the document context above. If applicable, mention which section or page numbers contain the answer.`;
    } else if (action === 'summarize') {
      prompt = `Here is the content of the PDF document:
--- DOCUMENT START ---
${safeTextContext}
--- DOCUMENT END ---

Please generate a comprehensive, structured summary of this document including:
1. Executive Summary (2-3 sentences overview)
2. Core Themes & Main Arguments
3. Key Takeaways & Action Items
4. Target Audience or Purpose`;
    } else if (action === 'key-points') {
      prompt = `Here is the content of the PDF document:
--- DOCUMENT START ---
${safeTextContext}
--- DOCUMENT END ---

Please extract the most critical key points, statistics, dates, figures, and actionable conclusions from this document as clear bullet points.`;
    } else if (action === 'outline') {
      prompt = `Here is the content of the PDF document:
--- DOCUMENT START ---
${safeTextContext}
--- DOCUMENT END ---

Please analyze this document and generate a clean, hierarchical outline / table of contents with sections, subsections, and topic descriptions.`;
    } else if (action === 'translate') {
      prompt = `Here is the content of the PDF document:
--- DOCUMENT START ---
${safeTextContext}
--- DOCUMENT END ---

Please translate the key contents and essential message of this document accurately into ${targetLanguage}. Maintain professional formatting.`;
    } else {
      return NextResponse.json({ error: 'Invalid action specified.' }, { status: 400 });
    }

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash',
      contents: prompt,
      config: {
        systemInstruction,
        temperature: 0.3,
      },
    });

    const answer = response.text || 'No response was generated by the model.';

    return NextResponse.json({
      success: true,
      result: answer,
      modelUsed: 'gemini-3.8-flash',
    });
  } catch (error: any) {
    console.error('Gemini API Route Error:', error);
    return NextResponse.json(
      {
        error:
          error?.message ||
          'Failed to communicate with the Gemini AI service. Please verify your network and credentials.',
      },
      { status: 500 }
    );
  }
}
